### ISSUE TITLE
What is the standard PHP version?

### ISSUE THREAD

**Issue by k00ni** [zozlak/easyRdfParserPerf#2]
From version to version PHP receives changes and improvements. We should set a fixed PHP version to be used for a given test period. Affects at least `run.yml` because it doesn't set a specific PHP version as far as I can tell.

```yaml
# run.yml
name: run

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer update
      run: composer update
    - name: test
      run: php -f test.php
    - name: test old EasyRdf
      run: php -f testOldReleases.php
```

For now I propose **PHP 7.4**. What do you think?
